### ISSUE TITLE
Can't obtain absolute values for strengths

### ISSUE THREAD

**Issue by trilbytim** [AndiMb/eLamX2#1]
I'm unable to work out how to obtain the actual failure stress values. The failure body represents the shape of the failure envelope but does not seem to include any scale so I can't read off the actual values of stress. The Engineering Constants tab gives elastic properties but not strengths. The only way I can see to get a strength value is to open the calculation tab and progressively increase the applied load until one of the plies shows a critical failure index. This only gives first ply failure rather than ultimate strength. I assume that since the failure body is able to show Last Ply failure then the code must be able to calculate progressive fracture, but I can't see any way to access this.
Would it be possible to add first and last ply failure stresses and strains in the principle directions to the Engineering Constants tab? Or is there already some way to display this information that I haven't found?

**Comment by AndiMb** [comment]
Yes, this is a frequently asked question. We have avoided directly providing absolute strength values. We had a lot of use cases where people wanted to put the laminate strength value as strength values into another failure criteria of a finite element program. This a tremendous mistake and we don't want to mislead people to do so. In most of the cases there is no need for laminate strength values.

But there are to workarounds. The first one is your way. Just use the calculation tab and choose a loading condition. The ratios of the loads must correspond to the loads you want to analyse. And then multiply the load with the minimal reserve factor.

The second approach is to use the laminate failure body tab and choose last ply failure. Then export the raw data and you're getting a vtk file you can use with paraview. This file is a text file, and each point coordinate corresponds to a last ply failure loading condition. These are the absolute values of the last ply failure strength.

Do you think, it's a good decision to provide absolute strength value of the laminate?

**Comment by trilbytim** [comment]
Thank you for your reply, I can see why you wouldn't want to provide values that are potentially misleading, but if people are asking the question frequently then they must have their reasons! In my case we are trying to size some compressive test coupons. On the ASTM standard there is an equation relating flexural stiffness and failure strength with gauge length, thickness and width to ensure the sample fails by the correct mode and doesn't buckle. So we need the approximate expected compressive failure strength (along with expected flexural stiffness, which is specified) to be able to size our test coupons. I've been trying to show my colleagues the benefits of Open Source software so it was a bit embarrassing not to be able to give them these numbers so they had to use CODA!
I haven't been able to find the export option for the failure body, where is that? The only export I can find is to export the laminate stack.
Overall this is very good software though and I'm sure will get some of my colleagues away from their ancient versions of LAP for doing these kind of calculations.

**Comment by AndiMb** [comment]
Ok, I will have a look at this and see where these values can be provided with a hint, that these values should never be used in another failure criterion.

The fifth button (a paper with a red arrow) is the export raw data button. When the "Failure body"-tab of a laminate is marked, you will be able to export the data.

**Comment by trilbytim** [comment]
Ah, yes, that makes sense, I see it also exports the calculations when on that tab. Yes, I think providing the values with a hint for their applicability would be good. My own use case for this kind of laminate analysis software is mostly for getting approximate values that I can use for some form of hand calcs, sizing these mechanical test coupons is very typical of the kinds I things I am doing and I guess I'm not alone.
