### ISSUE TITLE
Stresses for asymmetric layup

### ISSUE THREAD

**Issue by sovsep** [AndiMb/eLamX2#10]
Hello,

I have writen a python code for CLT and using elamX2 for validation.
For symmetric layups the results much perfectly but  as asymmetry gets bigger the diffeence ins stresses get's also bigger.
Does elamX2 neglect "B" matrix for stress calculation or I am missing something?

Examples are in the attachment.
[clt_output.txt](https://github.com/AndiMb/eLamX2/files/12263001/clt_output.txt)
[elamx2_output.txt](https://github.com/AndiMb/eLamX2/files/12263017/elamx2_output.txt)

Thanks,
Sergej

**Comment by AndiMb** [comment]
Hi,

no, eLamX2 uses the B matrix.

I first checked the "Engineering constants". While I'm able to reproduce the eLamX2 results, I'm not able to reproduce your python results. You should use 1 / (2.52 mm * 6.83179e-06) which is 1 / ( t_tot * [ABD^-1]_{1,1} ). And the result should be something like 58085.

Are you able to provide the strains of the laminate calculated with your tool?

Andreas

**Comment by sovsep** [comment]
Hello Andreas

Thanks, you put me on the right path. After you have asked for the laminate strains, I have noticed that my strains have wrong signes. The mistake was in the summing of the B matrix, signes of the B matrix were also wrong. Now I get consistent results with elamX2.
[clt_output.txt](https://github.com/AndiMb/eLamX2/files/12306686/clt_output.txt)

Regards,
Sergej
