### ISSUE TITLE
New failure criterion

### ISSUE THREAD

**Issue by cristipurdel** [AndiMb/eLamX2#6]
maximum stress criterion is looking at all 5 RFs based on the allowables from S11c, S11t, S22c, S22t and S12s

Would it be possible to add a new failure criterion to look only at the fibre RF, e.g. only considering the S11c, S11t?

**Comment by AndiMb** [comment]
This is a nice idea. 

With a small workaround this is already possible. Use very high values für the yield stresses R in the direction you want to ignore. So the reserve factor is very small for all stresses and the fibre RF will be the highes.
